firefox: Fix v130 riscv build with JIT
Provide missing function that other architectures all seem to have.

/var/tmp/portage/www-client/firefox-130.0.1/work/firefox-130.0.1/js/src/wasm/WasmCode.cpp:142:33: error: use of deleted
 function 'static void js::jit::MacroAssembler::patchFarJump(uint8_t*, uint8_t*)'