zsbl: Fix build to use PIE
Without the code relocations, ZSBL does not modify the FDT properly
among many other problems. The bare-metal binutils won't link
position-independent executables. Force GCC to use /usr/bin/ld. Also
avoid the use of SSP, which results in undefined references like

> /usr/bin/ld: /usr/riscv64-unknown-elf/include/ssp/string.h:84:(.text.fdt_packblocks_+0x8e): undefined reference to `memmove'
> /usr/bin/ld: /usr/riscv64-unknown-elf/include/ssp/string.h:84:(.text.fdt_packblocks_+0x11a): undefined reference to `memmove'
> /usr/bin/ld: /usr/riscv64-unknown-elf/include/ssp/string.h:84:(.text.fdt_splice_+0xca): undefined reference to `memmove'

since we're not using libc. This results in similar behavior to the
Sophgo build.